"""Persistence ports shared by CLI file storage and Web PostgreSQL storage.

Domain services receive this interface. Resource directories contain uploaded originals,
parser caches and exports; mutable workflow state must use these methods.
"""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol, runtime_checkable

from ..glossary.store import GlossaryTerm
from ..ingest.models import Chapter, Document

STATUS_PENDING = "pending"
STATUS_DONE = "done"


@runtime_checkable
class ArtifactStorage(Protocol):
    def read_artifact(self, key: str) -> Any | None: ...
    def write_artifact(self, key: str, value: Any) -> None: ...
    def delete_artifact(self, key: str) -> None: ...
    def list_artifacts(self, prefix: str = "") -> list[str]: ...
    def append_artifact_record(self, key: str, record: dict) -> None: ...
    def read_artifact_records(self, key: str) -> list[dict]: ...


@runtime_checkable
class Storage(ArtifactStorage, Protocol):
    # Read-only path attributes: implementations expose @property (FileStorage / PostgresStorage).
    @property
    def run_dir(self) -> str: ...

    @property
    def source_dir(self) -> str: ...

    @property
    def reviews_dir(self) -> str: ...

    def exists(self) -> bool: ...
    def init_from_document(self, doc: Document) -> dict: ...
    def stage_document(self, doc: Document, *, source_hash: str | None = None) -> dict: ...
    def begin_initialization(self, source_hash: str) -> None: ...
    def finish_initialization(self) -> None: ...
    def ensure_source_identity(
        self, input_path: str, *, actual_sha256: str | None = None
    ) -> str: ...
    def close(self) -> None: ...
    def lock(self) -> AbstractContextManager[None]: ...
    def state_lock(self) -> AbstractContextManager[None]: ...
    def assemble_lock(self) -> AbstractContextManager[None]: ...
    def create_export_snapshot(self, *, actual_sha256: str) -> Any: ...

    def save_manifest(self, manifest: dict) -> None: ...
    def load_manifest(self) -> dict: ...
    def set_chapter_status(self, ci: int, status: str) -> None: ...
    def pending_chapters(self) -> list[int]: ...
    def save_chapter(self, chapter: Chapter) -> None: ...
    def save_chapter_with_status(self, chapter: Chapter, status: str) -> None: ...
    def load_chapter(self, ci: int) -> Chapter: ...

    def save_context(self, data: dict) -> None: ...
    def load_context(self) -> dict | None: ...
    def save_annotation_contexts(self, data: dict) -> None: ...
    def load_annotation_contexts(self) -> dict | None: ...
    def save_analysis(self, data: dict) -> None: ...
    def load_analysis(self) -> dict | None: ...
    def save_report(self, data: dict) -> None: ...
    def load_report(self) -> dict | None: ...
    def save_usage(self, data: dict) -> None: ...
    def load_usage(self) -> dict | None: ...
    def prepare_usage_commit(self, ledgers: dict[str, dict]) -> None: ...
    def recover_usage(self) -> None: ...
    def record_timing(self, record: dict[str, Any]) -> dict[str, Any]: ...
    def load_latest_review_result(self) -> dict | None: ...
    def batch_glossary_key(self, start_index: int, count: int) -> str: ...
    def completed_batch_glossary_keys(self, chapter: int) -> set[str]: ...

    def log_event(self, event: str, **data: Any) -> None: ...
    def list_events(self, *, event_type: str | None = None, limit: int = 200) -> list[dict]: ...
    def get_term(self, source: str) -> GlossaryTerm | None: ...
    def upsert_term(self, term: GlossaryTerm, chapter: int | None = None) -> str: ...
    def all_terms(self) -> list[GlossaryTerm]: ...
    def terms_in(self, terms: list[GlossaryTerm], text: str) -> list[GlossaryTerm]: ...
    def terms_in_text(self, text: str) -> list[GlossaryTerm]: ...
    def resolve_term(self, source: str, target: str) -> bool: ...
    def delete_term(self, source: str) -> bool: ...
    def mark_conflicts_resolved(self, source: str) -> None: ...
    def open_conflicts(self) -> list[dict]: ...
    def stats(self) -> dict[str, int]: ...
